# Alignment configuration
# Alignment strategy
alignment_type: "HNB"    # Alignment type: "HNB", "SB", "FT"

# What to align
align_image: false       # Learn an alignment for the image encoder
align_text: true        # Learn an alignment for the text encoder

# Fine-tuning specific settings (only used with FT alignment)
ft_image: false         # Fine-tune image encoder (only used with FT)
ft_text: false          # Fine-tune text encoder (only used with FT)
